# Generated by Django 3.0.1 on 2019-12-23 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tenant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=250, verbose_name='First name')),
                ('last_name', models.CharField(max_length=250, verbose_name='Last name')),
                ('date_of_birth', models.DateField(blank=True, db_index=True, null=True)),
                ('phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='Phone num')),
                ('photo', models.ImageField(blank=True, help_text='Photo of the tenant', null=True, upload_to='tenant', verbose_name='Photo')),
                ('notes', models.TextField(blank=True, null=True)),
            ],
            options={
                'ordering': ['first_name', 'last_name'],
            },
        ),
        migrations.AddIndex(
            model_name='tenant',
            index=models.Index(fields=['first_name', 'last_name'], name='mycore_tena_first_n_59e684_idx'),
        ),
    ]
