# Generated by Django 3.0.1 on 2019-12-24 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mycore', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='sex',
            field=models.CharField(default='M', max_length=1),
        ),
    ]
