# Generated by Django 3.0.1 on 2020-01-19 12:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mycore', '0002_tenant_sex'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tenant',
            options={'ordering': ['first_name', 'last_name'], 'permissions': [('can_comment', 'Can user to make a comment')]},
        ),
    ]
